# Generated by Django 4.0.4 on 2022-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competition_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('bg_photo', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
